import {useState} from 'react'

import Head from 'next/head'

import Container from '@mui/material/Container'
import Paper from '@mui/material/Paper';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import Grid from '@mui/material/Grid';
import Alert from '@mui/material/Alert';
import  AlertTitle from '@mui/material/AlertTitle';


import NavBar from '../components/NavBar'
import Title from '../components/Title'
import FavouriteBooks from '../components/FavouriteBooks'

const FAVOURITE_BOOKS = [
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    rating: 9
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    rating: 8
  }
]

export default function Home() {
  const [error, setError] = useState("")
  const [bookList, newBookList] = useState([...FAVOURITE_BOOKS])
  const [bookTitle, setBookTitle] = useState("")
  const [author, setAuthor] = useState("")
  const [rating, setRating] = useState("")


  const isNotNumber = (value) => {
    return !isNaN(value)
  }

  const onAddBookClick = () => {
    let favouriteBook = {
      title: bookTitle,
      author: author,
      rating: rating
  }

  if(bookTitle.trim() === "" || author.trim() === ""  || rating.trim() === "") {
    setError("Please enter all of the values")
    return
  }
  if(!isNotNumber(rating)) {
    setError(`${rating} is not a valid number`)
    return
  }
    let updatedBookList = [...bookList, favouriteBook]
    newBookList(updatedBookList)
    setError("")
  }

  const onClickFunctionCall = (e) => {
    e.preventDefault()
    onAddBookClick() 
    setAuthor("")
    setBookTitle("")
    setRating("")
  }

  return (
    <div>
      <Head>
        <title>Library App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar title={"Our Library"} />
      <main>
        <Container sx={{paddingTop: '2rem'}} maxWidth="md">
           <Paper sx={{ p: 2, display: 'flex', flexDirection: 'column', marginBottom: "2rem"}}>
              <Title>Add a New Favourite</Title>
              <form> 
                <Grid container spacing={3}>
                  <Grid item xs={12} sm={6}>
                    <TextField
                      required
                      id="title"
                      name="title"
                      label="Book Title"
                      fullWidth
                      variant="standard"
                      value={bookTitle}
                      onChange={(event)=> { setBookTitle(event.target.value) }}
                    />
                  </Grid>
                  <Grid item xs={10} sm={4}>
                    <TextField
                      required
                      id="author"
                      name="author"
                      label="Author"
                      fullWidth
                      variant="standard"
                      value={author}
                      onChange={(event)=> { setAuthor(event.target.value) }}
                    />
                  </Grid>
                  <Grid item xs={10} sm={4}>
                    <TextField
                      required
                      id="rating"
                      name="rating"
                      label="Rating"
                      fullWidth
                      variant="standard"
                      value={rating}
                      onChange={(event)=> { setRating(event.target.value) }}
                    />
                  </Grid>
                  <Grid item xs={2} sm={2}>
                    <Button variant="contained"  
                     onClick={onClickFunctionCall} 
                     sx={{ mt: 1.5, ml: 1 }}>Add</Button>
                    
                  </Grid>
                  <Grid item xs={10}>
                  {error !== "" &&
                  <Alert severity="error"><AlertTitle>Error</AlertTitle>{error}</Alert>
                }
              </Grid>  
                </Grid>
              </form>
           </Paper>
          <FavouriteBooks books={bookList} />

        </Container>
      </main>
    </div>
  )
}
