import Head from 'next/head'
import Typography from '@mui/material/Typography';
import { Container } from '@mui/system';

import ResourcesList from '../Components/JSArticles.js';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Assignment 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <main>

        <Container maxWidth="md">
          
            <Typography variant="h2" component="h2" color="primary" align="center">
              Assignment 2 - React Componenets and Styling
            </Typography>
            <Typography variant="p" component="p" color="secondary" align="center">
             Here's a list of awesome resources that you can uses
            </Typography>
            <ResourcesList/>
        </Container>
        
      </main>
    </div>
  )
}
